install:
  - rm -rf public || exit 0
before_script:
  - git submodule update --remote themes/minimal
script:
  - binaries/hugo
deploy:
  provider: pages
  repo: ProvTools/provtools.github.io
  target_branch: master
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: provtools.org
  name: Travis
notifications:
  slack: endtoendprovenance:qqw61OZw9wGxFCX9mtotxJjH
