before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install hugo
script:
  - hugo --theme=minimal --buildDrafts
deploy:
  provider: pages
  repo: ProvTools/provtools.github.io
  target_branch: master
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: provtools.org
  name: Travis
notifications:
  slack: endtoendprovenance:qqw61OZw9wGxFCX9mtotxJjH
